### ISSUE TITLE
R2js: __.Sys__info is not a function

### ISSUE THREAD

**Issue by yannrichet** [yannrichet/rsession#29]
with variables: {}
 because: TypeError: __this__.Sys__info is not a function in <eval> at line number 1
R: Failed to evaluate code
```{js}
math.squeeze(math.subset(__this__.Sys__info(), R._index('release')))
```
 with variables: {}
 because: TypeError: __this__.Sys__info is not a function in <eval> at line number 1
R!
    at org.math.R.R2jsSession.silentlyRawEval(R2jsSession.java:2522)
    at org.math.R.Rsession.rawEval(Rsession.java:924)
    at org.math.R.Rsession.rawEval(Rsession.java:944)
    at org.math.R.Rsession.eval(Rsession.java:996)
    at org.funz.script.RMathExpression.printInformation(RMathExpression.java:387)
    at org.funz.script.RMathExpression.initR(RMathExpression.java:221)
    at org.funz.script.RMathExpression.<init>(RMathExpression.java:196)
    at org.funz.api.AbstractShell.setInputModel(AbstractShell.java:201)
    at org.funz.api.Shell_v1.<init>(Shell_v1.java:71)
    at org.funz.main.RunDesign.main(RunDesign.java:292)
org.math.R.Rsession$RException: Failed to evaluate code

**Comment by yannrichet** [comment]
not reproduce with current version
