### ISSUE TITLE
session.loadPackage(); resulted in java.net.SocketException: Broken pipe

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yannrichet/rsession#4]
```
What steps will reproduce the problem?
1. On MacOSX, with R 2.15.2 and JDK6
2. Rsession session = Rsession.newInstanceTry(System.out, null);
    session.loadPackage("robust");

What is the expected output? What do you see instead?
Evaluation of expressions work, but load libraries fail
run:
! No Rserve conf given. Trying to use R://localhost
[eval] library(robust)
!! [exception] eval failed
java.net.SocketException: Broken pipe
  library(robust)
  request package robust loading...
    at java.net.SocketOutputStream.socketWrite0(Native Method)
!! [exception] eval failed
  loadedpacks<-.packages()
!! [exception] eval failed
  is.element(set=loadedpacks,el='robust')
  package robust is not loaded.
!! [exception] eval failed
  rm(loadedpacks)
!   package robust loading failed.
[eval] rnorm(1000)
!! [exception] eval failed
  rnorm(1000)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:124)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:230)
    at org.rosuda.REngine.Rserve.RConnection.parseAndEval(RConnection.java:451)
    at org.rosuda.REngine.REngine.parseAndEval(REngine.java:108)
    at org.math.R.Rsession.silentlyEval(Rsession.java:965)
    at org.math.R.Rsession.silentlyEval(Rsession.java:941)
    at org.math.R.Rsession.isPackageLoaded(Rsession.java:601)
    at org.math.R.Rsession.loadPackage(Rsession.java:839)
    at rsessiontest.RSessionTest.main(RSessionTest.java:63)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:124)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:230)
    at org.rosuda.REngine.Rserve.RConnection.parseAndEval(RConnection.java:451)
    at org.rosuda.REngine.REngine.parseAndEval(REngine.java:108)
    at org.math.R.Rsession.silentlyEval(Rsession.java:965)
    at org.math.R.Rsession.silentlyEval(Rsession.java:941)
    at org.math.R.Rsession.isPackageLoaded(Rsession.java:614)
    at org.math.R.Rsession.loadPackage(Rsession.java:839)
    at rsessiontest.RSessionTest.main(RSessionTest.java:63)
java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:124)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:205)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:180)
    at org.rosuda.REngine.Rserve.protocol.RTalk.request(RTalk.java:250)
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:230)
    at org.rosuda.REngine.Rserve.RConnection.parseAndEval(RConnection.java:451)
    at org.rosuda.REngine.REngine.parseAndEval(REngine.java:108)
    at org.math.R.Rsession.silentlyEval(Rsession.java:965)
    at org.math.R.Rsession.eval(Rsession.java:997)
    at org.math.R.Rsession.eval(Rsession.java:1016)
    at rsessiontest.RSessionTest.main(RSessionTest.java:65)
BUILD SUCCESSFUL (total time: 2 seconds)

What version of the product are you using? On what operating system?
Mac OSX 10.7, JDK 6, R 2.15.2

Please provide any additional information below.
Interestingly, I have a Macbook Pro and iMac, with the same configs. The same 
programs works on the Macbook Pro but fails on iMac. Still haven't figured out 
what caused the issue.
```

Original issue reported on code.google.com by `m.sug...@gmail.com` on 20 Nov 2012 at 8:27

**Comment by yannrichet** [comment]
This might be due to a previous running instance of Rserve which needs to be killed befaore launching a new proper one.
